# Generated by Django 2.1.9 on 2019-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_user_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
